name: Compile Jar Package

on: 
  push:
    tags:
    - 'v*'  
jobs:
  build:
    runs-on: self-hosted
    permissions: write-all
    steps:
    - name: Maven Package
      run: ./mvnw clean package
    
    - run: mkdir staging && cp target/*.jar staging

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV  
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        # GitHub secret token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        prerelease: false
        title: "Release ${{ env.RELEASE_VERSION }}"
        # Assets to upload to the release
        files: |
          staging/*.jar
